= CalConnect Guide: Alignment of CalConnect practices towards WTO TBT Principles for the Development of International Standards, Guides and Recommendations
:title: Alignment to international principles -- WTO TBT principles for the Development of International Standards, Guides and Recommendations
:docnumber: 10100
:status: published
:doctype: report
:edition: 1
:copyright-year: 2019
:revdate: 2019-03-15
:published-date: 2019-03-15
:language: en
:technical-committee: PUBLISH
:draft:
:toc:
:stem:
:xrefstyle: short
:imagesdir: images
:docfile: cc-10100.adoc
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim of facilitating interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
CalConnect documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.


:sectnums!:
== Introduction

Amongst CalConnect's goals is to facilitate interoperable technologies
across geographical and geopolitical barriers.

As an international standardizing body, CalConnect has agreed to operate
in accordance to principles stated in the WTO TBT Agreement (<<WTOTBTP>>)
to facilitate the reduction of trade barriers worldwide.

In particular, this document provides description on how CalConnect
implements the TBT principles for international standardization bodies
stated in the "`Decision of the Committee on Principles for the Development of International Standards, Guides and Recommendations with relation to Articles 2, 5 and Annex 3 of the Agreement`" of <<WTOTBTP>>.


:sectnums:
== Scope

This document describes the alignment of CalConnect practices and
processes in their alignment to WTO TBT Principles, stated in
the "`Decision of the Committee on Principles for the Development of International Standards, Guides and Recommendations with relation to Articles 2, 5 and Annex 3 of the Agreement`" of <<WTOTBTP>>.

Actual practices in the CalConnect standardization process are
described in CalConnect directives. The goal of this document
is to describe how current practices align to the principles;
this document does not modify current or demand any
additional practice.


[bibliography]
== Normative references

* [[[WTOTBTP,WTO TBT Principles]]], _Annex 2: Decision of the Committee on Principles for the Development of International Standards, Guides and Recommendations with relation to Articles 2, 5 and Annex 3 of the Agreement; Decisions and recommendations adopted by the TBT Committee since 1 January 1995: Annexes to Part 1; WTO Agreements Series: Technical Barriers to Trade_, World Trade Organization

* [[[CC10001,CC/DIR 10001]]], _CalConnect Directive: Standardization and publication_

* [[[CC10002,CC/DIR 10002]]], _CalConnect Directive: Document requirements_

* [[[CC10003,CC/DIR 10003]]], _CalConnect Directive: Intellectual property rights policy_


[[terms]]
== Terms, definitions and abbreviations

=== Terms and definitions

==== international standardizing body

body that publishes international standards

==== CalConnect participants

participants in CalConnect activities, including all members of CalConnect,
experts participating on behalf of CalConnect liaison and partnership organizations




[[abbrev]]
=== Abbreviations

WTO:: World Trade Organization

TBT:: Technical Barriers to Trade


== WTO TBT principle 1: Transparency

=== Principles

[quote,World Trade Organization,"WTOTBTP,clause=1,paragraph=1"]
____
All essential information regarding current work programmes, as well as on proposals for standards, guides and recommendations under consideration and on the final results should be made easily accessible to at least all interested parties in the territories of at least all WTO Members.

Procedures should be established so that adequate time and opportunities are provided for written comments. The information on these procedures should be effectively disseminated.
____

Essential information regarding the current work programs at CalConnect,
as well as proposals for standardization work items, covering all
standards, guides and recommendations, are made readily accessible
on the Internet at the (<<CDR>>) free of charge.
This website is available to all WTO Members with Internet access.

The CalConnect standardization processes and procedures are described
in CalConnect directives (see <<CC10001>>, <<CC10002>> and <<CC10003>>),
which fulfill the requirements and are publicly available on <<CDR>>.


=== Requirements

The WTO TBT decision specifically states that "`essential information`"
should be provided according to the following requirements.

==== Early notice of standards development

[quote,World Trade Organization,"WTOTBTP,clause=1.a."]
____
{empty}a. the publication of a notice at an early appropriate stage, in such a manner as to enable interested parties to become acquainted with it, that the international standardizing body proposes to develop a particular standard;
____

<<CC10001,clause="6.6.1.3.a">> specifies that an accepted standardization
project proposal shall be listed in the CalConnect project registry.



==== Notification to members of standardizing body

[quote,World Trade Organization,"WTOTBTP,clause=1.b."]
____
{empty}b. the notification or other communication through established mechanisms to members of the international standardizing body, providing a brief description of the scope of the draft standard, including its objective and rationale. Such communications shall take place at an early appropriate stage, when amendments can still be introduced and comments taken into account;
____

<<CC10001,clause="6.6.1.3.b">> specifies that an accepted standardization
project proposal shall be announced to CalConnect members at an early enough stage
to facilitate amendments and comments.

[[draft-availability]]
==== Draft availability to members

[quote,World Trade Organization,"WTOTBTP,clause=1.c."]
____
{empty}c. upon request, the prompt provision to members of the international standardizing body of the text of the draft standard;
____

* <<CC10001,clause="6.6.7.b">> specifies that an a new draft version at the Preparatory
stage should be announced to all TCs;

* <<CC10001,clause="6.6.7.c">> specifies that an a new draft version at a development
stage may be announced to the CalConnect-wide membership for comments; and


==== Adequate time for membership comments

//* <<CC10001,clause="6.6.7.d">> specifies that a draft version may be posted for external

[quote,World Trade Organization,"WTOTBTP,clause=1.d."]
____
{empty}d. the provision of an adequate period of time for interested parties in the territory of at least all members of the international standardizing body to make comments in writing and take these written comments into account in the further consideration of the standard;
____

<<CC10001,clause="7">> specifies that a public review period of 60 days
is open to all interested parties prior to adoption of a standard.


==== Prompt publication notice

[quote,World Trade Organization,"WTOTBTP,clause=1.e."]
____
{empty}e. the prompt publication of a standard upon adoption; and
____

<<CC10001,clause="6.6.9.1">> specifies that a standard once approved and published
will be made available on the public <<CDR>>.


==== Publication of work program

[quote,World Trade Organization,"WTOTBTP,clause=1.f."]
____
{empty}f. to publish periodically a work programme containing information on the standards currently being prepared and adopted.
____


<<CC10001,clause="6.6.9.3">> specifies that all CalConnect projects are
registered in the public <<CDR>>.


==== Availability over the Internet

[quote,World Trade Organization,"WTOTBTP,clause=1,paragraph=2"]
____
It is recognized that the publication and communication of notices, notifications, draft standards, comments, adopted standards or work programmes electronically, via the Internet, where feasible, can provide a useful means of ensuring the timely provision of information. At the same time, it is also recognized that the requisite technical means may not be available in some cases, particularly with regard to developing countries. Accordingly, it is important that procedures are in place to enable hard copies of such documents to be made available upon request.
____

Publication and communication of notices, notifications, draft standards, comments, adopted standards or work programmes of CalConnect are all performed through the Internet.

In particular, the <<CDR>> provides timely information of the following:

. standards, draft standards, adopted standards;
. standards work programs and notifications; and
. comments solicitation notices.

The postal address of CalConnect is given on all CalConnect documents
for which hard copies of such documents can be requested through
a fair monetary sum, as determined by the Executive Director on a case by case basis.


== Openness

=== Non-discrimination in participation

[quote,World Trade Organization,"WTOTBTP,clause=2,paragraph=1"]
____
Membership of an international standardizing body should be open on a non-discriminatory basis to relevant bodies of at least all WTO Members. This would include openness without discrimination with respect to the participation at the policy development level and at every stage of standards development, such as the:

a. proposal and acceptance of new work items;

b. technical discussion on proposals;

c. submission of comments on drafts in order that they can be taken into account;

d. reviewing existing standards;

e. voting and adoption of standards; and

f. dissemination of the adopted standards.
____


CalConnect is an international standards body that welcomes participation
from commercial, non-commercial, governmental bodies and individuals
through its membership system (see <<CCMEMBERS>>).

Development of CalConnect Policies are driven and overseen by the
elected Board of Directors of CalConnect, and their enactment and
approval involve the CalConnect membership.

As described in <<CC10001>>, CalConnect members are allowed to
participate in every stage of standards development:

. full members are allowed to propose new work items (<<WTOTBTP,clause="2.a">>),
participate in standards development activities (<<WTOTBTP,clause="2.b-d">>),
vote on adoption of standards (<<WTOTBTP,clause="2.e">>),
and disseminate standards within the membership organization (<<WTOTBTP,clause="2.f">>);

. supporting members are allowed to receive notification of newly proposed standards
and submit their comments during the public review period (<<WTOTBTP,clause="2.c">>),
and disseminate the adopted standards within the organization (<<WTOTBTP,clause="2.f">>);

. external liaison and partnership organizations are allowed varied participation
rights depending on the particular agreement CalConnect has with them, for example,
ISO/TCs that CalConnect liaisons with are allowed to fully participate in the
CalConnect standardization process.

[quote,World Trade Organization,"WTOTBTP,clause=2,paragraph=2"]
____
Any interested member of the international standardizing body, including especially developing country Members, with an interest in a specific standardization activity should be provided with meaningful opportunities to participate at all stages of standard development. It is noted that with respect to standardizing bodies within the territory of a WTO Member that have accepted the Code of Good Practice for the Preparation, Adoption and Application of Standards by Standardizing Bodies (Annex 3 of the TBT Agreement) participation in a particular international standardization activity takes place, wherever possible, through one delegation representing all standardizing bodies in the territory that have adopted, or expected to adopt, standards for the subject-matter to which the international standardization activity relates. This is illustrative of the importance of participation in the international standardizing process accommodating all relevant interests.
____

CalConnect operates under a non-discrimination principle such that membership
categories do not distinguish the origin of organizations between developing and
developed countries.

This practice effectively allows participation of having one
delegation representing multiple standardizing bodies at CalConnect
international standardization activities as a single member, as specified in
the last paragraph in (<<WTOTBTP,clause="2">>).


== Impartiality and consensus

[quote,World Trade Organization,"WTOTBTP,clause=3,paragraph=1"]
____
All relevant bodies of WTO Members should be provided with meaningful opportunities to contribute to the elaboration of an international standard so that the standard development process will not give privilege to, or favour the interests of, a particular supplier/s, country/ies or region/s. Consensus procedures should be established that seek to take into account the views of all parties concerned and to reconcile any conflicting arguments.
____

CalConnect standardization processes is consensus-based and does not
provide privilege to any particular entity. <<CC10001>> fully describes
the CalConnect standardization processes, which employs a bottom-up
consensus process.

In particular, the application of requirements of <<WTOTBTP,clause="3">>:

[quote,World Trade Organization,"WTOTBTP,clause=3,paragraph=2"]
____
Impartiality should be accorded throughout all the standards development process with respect to, among other things:

a. access to participation in work;

b. submission of comments on drafts;

c. consideration of views expressed and comments made;

d. decision-making through consensus;

e. obtaining of information and documents;

f. dissemination of the international standard;

g. fees charged for documents;

h. right to transpose the international standard into a regional or national standard; and

i. revision of the international standard.
____


. Participation of work is at the TC-level as specified in <<CC10001,clause="6.4">>,
which is open to all full members of CalConnect (aligns with <<WTOTBTP,clause="3.a">>);

. Submission of comments at stages relevant to comments, including
the Committee stage <<CC10001,clause="6.6.4">>, Approval stage <<CC10001,clause="6.6.4">>
as well as the Pre-publication stages <<CC10001,clause="6.6.8">> are open to all
eligible bodies (aligns with <<WTOTBTP,clause="3.b">>);

. The CalConnect commenting process (<<CC10001,clause="8.1">>)
specifies that comments are considered by the TCC and the TC that owns the
standardization work item. Comments and feedback are judged according to
their technical contributions in an impartial way
(<<CC10001,clause="8.4">>) (aligns with <<WTOTBTP,clause="3.c">>).

. The CalConnect standardization process is fully based on a
bottom-up consensus model resolved via balloting (<<CC10001,clause="8.1">>),
with the scope being the technical body in charge, in this case
the owning TC at the earlier stages, the TCC and the membership body
at later stages (aligns with <<WTOTBTP,clause="3.d">>);

. CalConnect standardization work items and their information can
  be obtained directly from the <<CDR>> (aligns with <<WTOTBTP,clause="3.e">>).

. CalConnect standardization work items and their information can
  be disseminated to the membership organization <<CDR>> (aligns with <<WTOTBTP,clause="3.f">>).

. CalConnect standardization work items are provided free-of-charge (<<CC10001,clause="8.4">>) (aligns with <<WTOTBTP,clause="3.g">>).

. CalConnect allows regional or national standards bodies to transpose
  a CalConnect standard into a regional or national standard,
  under an official, non-discriminatory and mutually-beneficial arrangement
  in accordance with the following requirements:
  (aligns with  <<WTOTBTP,clause="3.h">>)

.. The arrangement must be officially settled by both parties prior to transposition;

.. The relationship between the transposed CalConnect standard and the
  regional or national standard must be made clear to the reader, whether
  the transposition is:

*** identical (identical intention and content);
*** equivalent (identical intention but with minor modifications); or
*** unequal (identical intention, but with major modifications)

. CalConnect standardization work items are revised by the owning TC
  according to <<CC10001,clause="11">>, of which participation is open to all
  full members (aligns with <<WTOTBTP,clause="3.i">>).



== Effectiveness and relevance

[quote,World Trade Organization,"WTOTBTP,clause=4,paragraph=1"]
____
In order to serve the interests of the WTO membership in facilitating international trade and preventing unnecessary trade barriers, international standards need to be relevant and to effectively respond to regulatory and market needs, as well as scientific and technological developments in various countries. They should not distort the global market, have adverse effects on fair competition, or stifle innovation and technological development. In addition, they should not give preference to the characteristics or requirements of specific countries or regions when different needs or interests exist in other countries or regions. Whenever possible, international standards should be performance based rather than based on design or descriptive characteristics.
____

CalConnect is a membership-driven international standards organization that
aims to facilitate interoperability of technical systems, often through
standardization of innovative technologies
(<<CCMISSION,"Introduction to CalConnect: Overview">>).

Membership at CalConnect is open to all WTO members, and its standards
are widely impacting on a global scale (<<CCMEMBERS>>).

Standards created by CalConnect are performance-based, as in based
on sets of requirements rather than based on descriptive characteristics
(<<CC10001,clause=5.2>>).

[quote,World Trade Organization,"WTOTBTP,clause=4,paragraph=2"]
____
Accordingly, it is important that international standardizing bodies:

. take account of relevant regulatory or market needs, as feasible and appropriate, as well as scientific and technological developments in the elaboration of standards;

. put in place procedures aimed at identifying and reviewing standards that have become obsolete, inappropriate or ineffective for various reasons; and

. put in place procedures aimed at improving communication with the World Trade Organization.
____


CalConnect standardization work item initiation requirements (<<CC10001,clause=6.6.1.2.c-d>>)
aligns with <<WTOTBTP,clause="4.a">>.

<<CC10001,clause=11.1>> specifies the mandatory review period
for every CalConnect standard to be reviewed for relevance,
which aligns with <<WTOTBTP,clause="4.b">>.

In order to improve communication with the World Trade Organization,
CalConnect is a signatory of the <<WTOTBTCode>> and is listed on the <<WTOISOSIG>>.
The CalConnect standardization work program is provided at the <<CDR>> with regular updates, and is also linked from the <<WTOISOSIG>>.


== Coherence

[quote,World Trade Organization,"WTOTBTP,clause=5"]
____
In order to avoid the development of conflicting international standards, it is important that international standardizing bodies avoid duplication of, or overlap with, the work of other international standardizing bodies. In this respect, cooperation and coordination with other relevant international bodies is essential.
____

CalConnect maintains a number of liaisons and partnerships with
other international standardization bodies including ISO, OASIS
and M3AAWG in order to:

* coordinate to prevent duplication of work on standardization topics;
* cooperate and collaborate on standardization topics.


== Development dimension

[quote,World Trade Organization,"WTOTBTP,clause=6"]
____
Constraints on developing countries, in particular, to effectively participate in standards development, should be taken into consideration in the standards development process. Tangible ways of facilitating developing countries' participation in international standards development should be sought. The impartiality and openness of any international standardization process requires that developing countries are not excluded de facto from the process. With respect to improving participation by developing countries, it may be appropriate to use technical assistance, in line with Article 11 of the TBT Agreement. Provisions for capacity building and technical assistance within international standardizing bodies are important in this context.
____

CalConnect adheres to the principles that participation in
the standardization process should be fair and be based on
technical and market merit, regardless of the origin of the
participant.

To this end, CalConnect adopts the following practices
that are beneficial to developing countries:

* Our standards facilitates the ease of international trade;

* Our standards are open and free, available on the <<CDR>> through the Internet;

* Contribution to standards can be done over phone, email or the Internet;

* Non-members can get directly in touch about a standardization subject matter at certain events, including CalConnect Hackathons;

* Our general mailing list is open for all interested in the subject;

* Our public commenting process (<<CC10001,clause="8">>) is open to everyone;

* Our supporting membership category provides a large discount
  compared to full membership allowing smaller organizations
  and those from developing countries to participate and obtain
  visibility in the standardization process;

* Full membership fees for commercial vendors are considered on
  organizational revenue, allowing those from developing countries to
  benefit from a lower membership fee.
  In addition, membership fees for all other organizations and
  individual memberships are set low to ensure availability
  regardless of revenue or location.


[bibliography]
== Bibliography

* [[[CDR,CalConnect document registry]]], _CalConnect document registry_, https://standards.calconnect.org

* [[[CCMEMBERS,CalConnect members]]], _CalConnect members_, https://www.calconnect.org/membership-categories-and-fees

* [[[CCMISSION,Introduction to CalConnect]]], _Introduction to CalConnect_, https://www.calconnect.org/about

* [[[WTOISOSIG,WTO ISO Standards Information Gateway]]], _WTO ISO Standards Information Gateway_, https://tbtcode.iso.org/

* [[[WTOTBTCode,WTO TBT Code of Good Practice]]], _WTO TBT Code of Good Practice_, https://www.wto.org/english/tratop_e/tbt_e/tbt_e.htm
