= Decision of the Committee on Principles for the Development of International Standards, Guides and Recommendations with relation to Articles 2, 5 and Annex 3 of the Agreement
:doc-series: WTO Agreements Series

:secnums!:
== Decision footnote:[G/TBT/9, 13 November 2000, para. 20 and Annex 4]

The following principles and procedures should be observed, when international standards, guides and recommendations (as mentioned under Articles 2, 5 and Annex 3 of the TBT Agreement for the preparation of mandatory technical regulations, conformity assessment procedures and voluntary standards) are elaborated, to ensure transparency, openness, impartiality and consensus, effectiveness and relevance, coherence, and to address the concerns of developing countries.

The same principles should also be observed when technical work or a part of the international standard development is delegated under agreements or contracts by international standardizing bodies to other relevant organizations, including regional bodies.

:secnums:
== Transparency

All essential information regarding current work programmes, as well as on proposals for standards, guides and recommendations under consideration and on the final results should be made easily accessible to at least all interested parties in the territories of at least all WTO Members. Procedures should be established so that adequate time and opportunities are provided for written comments. The information on these procedures should be effectively disseminated.

In providing the essential information, the transparency procedures should, at a minimum, include:

. the publication of a notice at an early appropriate stage, in such a manner as to enable interested parties to become acquainted with it, that the international standardizing body proposes to develop a particular standard;

. the notification or other communication through established mechanisms to members of the international standardizing body, providing a brief description of the scope of the draft standard, including its objective and rationale. Such communications shall take place at an early appropriate stage, when amendments can still be introduced and comments taken into account;

. upon request, the prompt provision to members of the international standardizing body of the text of the draft standard;

. the provision of an adequate period of time for interested parties in the territory of at least all members of the international standardizing body to make comments in writing and take these written comments into account in the further consideration of the standard;

. the prompt publication of a standard upon adoption; and

. to publish periodically a work programme containing information on the standards currently being prepared and adopted.

It is recognized that the publication and communication of notices, notifications, draft standards, comments, adopted standards or work programmes electronically, via the Internet, where feasible, can provide a useful means of ensuring the timely provision of information. At the same time, it is also recognized that the requisite technical means may not be available in some cases, particularly with regard to developing countries. Accordingly, it is important that procedures are in place to enable hard copies of such documents to be made available upon request.

== Openness

Membership of an international standardizing body should be open on a non-discriminatory basis to relevant bodies of at least all WTO Members. This would include openness without discrimination with respect to the participation at the policy development level and at every stage of standards development, such as the:

. proposal and acceptance of new work items;

. technical discussion on proposals;

. submission of comments on drafts in order that they can be taken into account;

. reviewing existing standards;

. voting and adoption of standards; and

. dissemination of the adopted standards.

Any interested member of the international standardizing body, including especially developing country Members, with an interest in a specific standardization activity should be provided with meaningful opportunities to participate at all stages of standard development. It is noted that with respect to standardizing bodies within the territory of a WTO Member that have accepted the Code of Good Practice for the Preparation, Adoption and Application of Standards by Standardizing Bodies (Annex 3 of the TBT Agreement) participation in a particular international standardization activity takes place, wherever possible, through one delegation representing all standardizing bodies in the territory that have adopted, or expected to adopt, standards for the subject-matter to which the international standardization activity relates. This is illustrative of the importance of participation in the international standardizing process accommodating all relevant interests.

== Impartiality and Consensus

All relevant bodies of WTO Members should be provided with meaningful opportunities to contribute to the elaboration of an international standard so that the standard development process will not give privilege to, or favour the interests of, a particular supplier/s, country/ ies or region/s. Consensus procedures should be established that seek to take into account the views of all parties concerned and to reconcile any conflicting arguments.

Impartiality should be accorded throughout all the standards development process with respect to, among other things:

. access to participation in work;

. submission of comments on drafts;

. consideration of views expressed and comments made;

. decision-making through consensus;

. obtaining of information and documents;

. dissemination of the international standard;

. fees charged for documents;

. right to transpose the international standard into a regional or national standard; and

. revision of the international standard.

== Effectiveness and Relevance

In order to serve the interests of the WTO membership in facilitating international trade and preventing unnecessary trade barriers, international standards need to be relevant and to effectively respond to regulatory and market needs, as well as scientific and technological developments in various countries. They should not distort the global market, have adverse effects on fair competition, or stifle innovation and technological development. In addition, they should not give preference to the characteristics or requirements of specific countries or regions when different needs or interests exist in other countries or regions. Whenever possible, international standards should be performance based rather than based on design or descriptive characteristics.

Accordingly, it is important that international standardizing bodies:

. take account of relevant regulatory or market needs, as feasible and appropriate, as well as scientific and technological developments in the elaboration of standards;

. put in place procedures aimed at identifying and reviewing standards that have become obsolete, inappropriate or ineffective for various reasons; and

. put in place procedures aimed at improving communication with the World Trade Organization.

== Coherence

In order to avoid the development of conflicting international standards, it is important that international standardizing bodies avoid duplication of, or overlap with, the work of other international standardizing bodies. In this respect, cooperation and coordination with other relevant international bodies is essential.

== Development Dimension

Constraints on developing countries, in particular, to effectively participate in standards development, should be taken into consideration in the standards development process. Tangible ways of facilitating developing countries' participation in international standards development should be sought. The impartiality and openness of any international standardization process requires that developing countries are not excluded de facto from the process. With respect to improving participation by developing countries, it may be appropriate to use technical assistance, in line with Article 11 of the TBT Agreement. Provisions for capacity building and technical assistance within international standardizing bodies are important in this context.

